grails-app/domain/holder/EmailTemplate.groovy
package holder

import grails.core.GrailsApplication
import groovy.text.GStringTemplateEngine
import grails.plugin.asyncmail.AsynchronousMailMessage
import grails.plugin.asyncmail.AsynchronousMailService

import java.time.LocalDateTime

class EmailTemplate {
    AsynchronousMailService asynchronousMailService
    MailIndexService mailIndexService
    GrailsApplication grailsApplication
    SmsService smsService

    String name
    Room room
    String toAddress
    String ccAddress
    String bccAddress
    String tags
    String subject
    String body
    String phone
    String smsText
    Album attachments
    LocalDateTime dateCreated
    User userCreated
    LocalDateTime lastUpdated
    User userUpdated

    static engine = new GStringTemplateEngine()

    static belongsTo = [room: Room]

    static transients = [ 'tagList', 'mailIndexService', 'smsService', 'grailsApplication', 'asynchronousMailService' ]

    static constraints = {
        name nullable: false
        room nullable: true
        toAddress nullable: true
        ccAddress nullable: true
        bccAddress nullable: true
        tags nullable: true, maxSize: 512
        subject maxSize: 78
        body widget: 'textarea', maxSize: 32672
        phone nullable: true, maxSize: 512
        smsText nullable: true, widget: 'textarea', maxSize: 925
        attachments nullable: true
        dateCreated display: true
        userCreated display: false, editable: false // Think editable does nothing, and display: controls edit
        lastUpdated display: true
        userUpdated display: false, editable: false // Don't really want it nullable, but has to be
    }

    static mapping = {
        id defaultValue: "nextval('hibernate_sequence')"
        autowire true
        dateCreated defaultValue: "current_timestamp"
        userCreated defaultValue: '1'
        lastUpdated defaultValue: "current_timestamp"
        userUpdated defaultValue: '1'
        version defaultValue: '0'
    }

    def beforeValidate() {
        attachments?.beforeValidate()
        if (attachments?.photos?.size() == 0) {
            attachments = null
        }
    }

    Set<String> getTagList() {
//        def foo = Arrays.asList(*tags.split('\\|').findAll{it})
//        def bar = new HashSet(Arrays.asList(tags.split('\\|').findAll{it}))
//        def baz = new  HashSet(foo)
        return new HashSet(Arrays.asList(*(tags?:'').split('\\|').findAll{it}))
    }

    void setTagList(Collection<String> v) {
        this.tags = v.join('|')
        if (tags) {
            tags = '|' | tags | '|'
        }
    }


    List<String> bindAddresses(Map binding, String address) {
        Arrays.asList(engine.createTemplate(address ?: '').make(binding).toString().split(',')).collect {it.trim() }.findAll { it }
    }

    String bindSubject(Map binding) {
        engine.createTemplate(subject).make(binding).toString()
    }

    String bindBody(Map binding) {
        engine.createTemplate(body).make(binding).toString()
    }

    String bindSmsText(Map binding) {
        engine.createTemplate(smsText).make(binding).toString()
    }

    String bindPhone(Map binding) {
        engine.createTemplate(phone).make(binding).toString()
    }

    AsynchronousMailMessage sendMail(Map bindings, boolean enabled = true, List<Map> indexes = [], boolean smsEnabled = false) {
        def allBindings = [*: bindings, config: grailsApplication.config, principal: User.principal]
        List toAddresses = bindAddresses(allBindings, toAddress)
        List ccAddresses = bindAddresses(allBindings, ccAddress)
        List bccAddresses = bindAddresses(allBindings, bccAddress)
        int maxAttempts = Config.findByName(ConfigNameEnum.EMAIL_ENABLED).bool ? 3 : 0
        String theSubject = bindSubject(allBindings)
        AsynchronousMailMessage mm
        if (enabled) {
            mm = asynchronousMailService.sendMail {
                to toAddresses
                if (ccAddresses.size() > 0) {
                    cc ccAddresses
                }
                if (bccAddresses.size() > 0) {
                    bcc bccAddresses
                }
                subject theSubject
                text bindBody(allBindings)
                maxAttemptsCount maxAttempts
            }
            mailIndexService.create(mm, this, indexes)
        } else {
            log.warn("email disabled: ${toAddresses}: ${subject}")
        }
        if (smsEnabled && Config.findByName(ConfigNameEnum.SMS_ENABLED).bool) {
            def smsResult = smsService.send([to: bindPhone(allBindings), message: bindSmsText(allBindings)])
            log.debug "$smsResult"
        }
        mm
    }

//    static EmailTemplate findTemplate(String name, Room room) {
//        return findTemplate(name, null, room)
//    }

    static Map<EmailTemplate,Set<String>> findTemplates(String name, Collection<String> tagList) {
        return EmailTemplate.findAllByName(name).collectEntries {
            [(it): it.tagList.intersect(tagList)]
        }
    }

    static EmailTemplate findTemplate(String name, Collection<String> tagList = []) {
        return findTemplates(name, tagList).max {
            it.value.size()
        }.key
    }


    static EmailTemplate findTemplate(String name, Collection<String> tagList, Room room) {
//        Map<EmailTemplate,Set<String>> summary = findTemplates(name, tagList).
        //TODO need a better way of reporting template not found
          return findAllByName(name).findAll {tagList.containsAll(it.tagList) }.
                findAll { !it.room || it.room.has(room)}.
                sort { a, b ->
                        b.tagList.size() <=> a.tagList.size() ?: a.room && b.room ? b.room.level.id <=> a.room.level.id : a.room ? -1 : b.room ? 1 : 0
                }.find()
//        int maximumTags = summary.max { it.value.size() }.value.size()
//        for (int i = maximumTags; i >= 0; i--) {
//            for (Map.Entry<EmailTemplate,Set<String>> tmplt in summary.findAll { it.value.size() == i }.
//                    sort {a, b -> a.room && b.room ? b.level.id <=> a.level.id : a.room ? -1 : b.room ? 1 : 0 }) {
//                if (!tmplt.key.room || room.has(tmplt.key.room)) {
//                    return tmplt
//                }
//            }
//        }
//        return null
    }
}

//        static EmailTemplate findTemplate(String name, List<String> tagList, Room room) {
//        EmailTemplate t
//        List<String> ltagList = tagList ? tagList.collect {"|$it|"  } : null
////        String ltag = tag ? '%|' | tag | '|%' : null
//            // Try tag and room
//        Room aRoom = room
//        if (ltagList) {
//            for (String ltag in ltagList) {
//                t = EmailTemplate.findByNameAndTagsLikeAndRoom(name, ltag, aRoom)
//                if (t) {
//                    break;
//                }
//            }
//            while (aRoom && !t) {
//                // try tag and parent room
//                aRoom = aRoom.parent
//                // final time through the loop, room is null
//                for (String ltag in ltagList) {
//                    t = EmailTemplate.findByNameAndTagsLikeAndRoom(name, ltag, aRoom)
//                    if (t) {
//                        break;
//                    }
//                }
//            }
//        }
//        aRoom = room
//        if (!t) {
//            t = EmailTemplate.findByNameAndTagsAndRoom(name, null, aRoom)
//            while (aRoom && !t) {
//                // try just the room
//                aRoom = aRoom.parent
//                // final time through the loop, room is null
//                t = EmailTemplate.findByNameAndTagsAndRoom(name, null, aRoom)
//            }
//        }
//        return t
//    }

grails-app/controllers/holder/EmailTemplateController.groovy
package holder

import grails.plugin.springsecurity.annotation.Secured

@Secured('ROLE_ADMIN')
class EmailTemplateController {
    static scaffold = EmailTemplate

    def email(BulkEmailCommand bulkEmailCommand) {
        render view: 'email', model: [bulkEmailCommand: new BulkEmailCommand()]
    }

    def analyseEmail(EmailTemplate command) {
        // TODO what is this garbage?
        def emailTemplateCommandList =
                Perosn.currentGuests.collect { EmailTemplate.findTemplate(command.name, command.tags, command.room) }
        render view: 'analyseEmail', model: [personList: Person.currentGuests]
    }

    def copy(EmailTemplate emailTemplate) {
        EmailTemplate et = new EmailTemplate(
                name: emailTemplate.name,
                room: emailTemplate.room,
                toAddress: emailTemplate.toAddress,
                ccAddress: emailTemplate.ccAddress,
                bccAddress: emailTemplate.bccAddress,
                tags: emailTemplate.tags,
                subject: emailTemplate.subject,
                body: emailTemplate.body,
                attachments: emailTemplate.attachments
        )
        render view: 'create', model: [emailTemplate: et]
    }
}

grails-app/views/emailTemplate/analyseEmail.gsp
<%--
  Created by IntelliJ IDEA.
  User: chris
  Date: 8/8/21
  Time: 10:22 pm
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
</head>

<body>
<table>
<g:each in="${emailTemplateCommandList}" var="et">
    <tr>
        <td>${et.perosn.name}</td>
        <td>${et.emailTemplate.subject}</td>
    </tr>
</g:each>
</table>
</body>
</html>

grails-app/views/emailTemplate/email.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'emailTemplate.label', default: 'EmailTemplate')}" />
    <title><g:message code="default.email.label" args="[entityName]" /></title>
</head>
<body>
<a href="#create-emailTemplate" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
    </ul>
</div>
<div id="create-emailTemplate" class="content scaffold-create" role="main">
    <h1><g:message code="default.email.label" args="[entityName]" default="Send Email" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.emailTemplate}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.emailTemplate}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form resource="${this.emailTemplate}" method="POST">
        <fieldset class="form">
            %{--            <f:all bean="emailTemplate"/>--}%
            <f:field bean="bulkEmailCommand" property="templateName"/>
            <f:field bean="bulkEmailCommand" property="room"/>
            <f:field bean="bulkEmailCommand" property="tag"/>
            <f:field bean="bulkEmailCommand" property="alsoSendToBillingEmail"/>
            <f:field bean="bulkEmailCommand" property="toAddress"/>
            <f:field bean="bulkEmailCommand" property="ccAddress"/>
            <f:field bean="bulkEmailCommand" property="bccAddress"/>
            <f:field bean="bulkEmailCommand" property="body"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/emailTemplate/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'emailTemplate.label', default: 'EmailTemplate')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-emailTemplate" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-emailTemplate" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${emailTemplateList}" except="[]"/>

            <div class="pagination">
                <g:paginate total="${emailTemplateCount ?: 0}" />
            </div>
            <fieldset class="buttons">
                <g:link class="edit" action="edit" resource="${this.room}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                <g:link class="email" action="email" resource="${this.room}"><g:message code="default.button.email.label" default="Email" /></g:link>
            </fieldset>
        </div>
    </body>
</html>

grails-app/views/emailTemplate/show.gsp
<%@ page import="holder.User" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'emailTemplate.label', default: 'EmailTemplate')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-emailTemplate" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-emailTemplate" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="emailTemplate" />
            <g:form resource="${this.emailTemplate}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.emailTemplate}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <g:link class="copy" action="copy" resource="${this.emailTemplate}"><g:message code="default.button.copy.label" default="Copy" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    <table>
        <thead>
        <tr><th>Guest</th><th>Template ID</th><th>Template Tags</th><th>Template Room</th><th>Subject</th><th>Body</th></tr>
        </thead>
        <g:each in="${holder.Person.currentGuests}" var="person">
            <tr>
                <td>${person.name}</td>
                <g:set var="template" value="${holder.EmailTemplate.findTemplate(emailTemplate.name, person.tagList, person.contracts.sort {a,b -> b.dateCreated <=> a.dateCreated}.first().room)}"/>
%{--                <g:set var="bindings" value="${[config: grailsApplication.config, principal: User.principal, person: person, contract: person.contracts.find(), schedule: null, token: null, task: null]}"/>--}%
                <td>${template ? "$template.id" : 'No template found' }</td>
                <td>${template?.tagList?.size() > 0 ? "$template.tagList" : '' }</td>
                <td>${template?.room ? "$template.room" : '' }</td>
                <td>${template?.subject}</td>
                <td>${template?.body}</td>
            </tr>
        </g:each>
    </table>
    </body>
</html>